### ISSUE TITLE
这个可以提供数据来试一下吗？

### ISSUE THREAD

**Issue by gg22mm** [xiaofeng1990/ResNet-50-Keras#1]
这个可以提供数据来试一下吗？

**Comment by gg22mm** [comment]
哦。看到： allocation_picture.py 了

**Comment by xiaofeng1990** [comment]
代码有跟新，我还没更新，稍晚些我发你最新的代码




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaofeng1990/ResNet-50-Keras"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月27日(星期三) 下午4:13
收件人:&nbsp;"xiaofeng1990/ResNet-50-Keras"<ResNet-50-Keras@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaofeng1990/ResNet-50-Keras] 这个可以提供数据来试一下吗？ (#1)





 
Closed #1.

**Comment by gg22mm** [comment]
多谢大老哈。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xiaofeng1990"<notifications@github.com&gt;; 
发送时间: 2021年1月27日(星期三) 下午4:23
收件人: "xiaofeng1990/ResNet-50-Keras"<ResNet-50-Keras@noreply.github.com&gt;; 
抄送: "お第二世ぞ"<gg22mm@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [xiaofeng1990/ResNet-50-Keras] 这个可以提供数据来试一下吗？ (#1)





 代码有跟新，我还没更新，稍晚些我发你最新的代码 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "xiaofeng1990/ResNet-50-Keras"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2021年1月27日(星期三) 下午4:13 
 收件人:&amp;nbsp;"xiaofeng1990/ResNet-50-Keras"<ResNet-50-Keras@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [xiaofeng1990/ResNet-50-Keras] 这个可以提供数据来试一下吗？ (#1) 
 
 
 
 
 
   
 Closed #1.

**Comment by gg22mm** [comment]
期待。。 多谢大老哈~~~

**Comment by xiaofeng1990** [comment]
这是完整的代码，参考https://blog.csdn.net/koala_tree/article/details/78583979






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "xiaofeng1990/ResNet-50-Keras"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月27日(星期三) 下午4:26
收件人:&nbsp;"xiaofeng1990/ResNet-50-Keras"<ResNet-50-Keras@noreply.github.com&gt;;
抄送:&nbsp;"小风"<2840824715@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaofeng1990/ResNet-50-Keras] 这个可以提供数据来试一下吗？ (#1)





 
期待。。 多谢大老哈~~~
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

ResNet-keras.rar (837.53M, 2021年02月26日 20:22 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=76363832b4b293f9b8bd6b9b1631061d020f0c03030703511e040e51001c0000065215500608021f0403000a0850515752570d513021346056457657441c5f5741574b1c425046320e&t=exs_ftn_download&code=36820142

**Comment by gg22mm** [comment]
上面的代码看了，没有完整的例子，云里雾里。 我之前也看文档也做过一个，但是感觉精度不准确。 我怀疑是文档不行呢还是resnet本来就这样，这是我的例子：  https://github.com/gg22mm/python_resnet   ，所以说我要看看到底resnet能不能达到我的要请，还是我的代码有问题

**Comment by xiaofeng1990** [comment]
你这里没有验证集，你也没有设置，你也之设置了初始学习率，没有加入学习率的衰减，还有训练的epochs太小了，一般设置为100，然后加EarlyStopping回调，
你加我微信吧，17688738964




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaofeng1990/ResNet-50-Keras"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月28日(星期四) 上午10:06
收件人:&nbsp;"xiaofeng1990/ResNet-50-Keras"<ResNet-50-Keras@noreply.github.com&gt;;
抄送:&nbsp;"小风"<2840824715@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaofeng1990/ResNet-50-Keras] 这个可以提供数据来试一下吗？ (#1)





 
上面的代码看了，没有完整的例子，云里雾里。 我之前也看文档也做过一个，但是感觉精度不准确。 我怀疑是文档不行呢还是resnet本来就这样，这是我的例子：  https://github.com/gg22mm/python_resnet   ，所以说我要看看到底resnet能不能达到我的要请，还是我的代码有问题
